# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    old_password_encoder:
        class: Symfony\Component\Security\Core\Encoder\MessageDigestPasswordEncoder
        arguments: ["md5", false, 1]

    password_migration_authenticator:
        class:     AppBundle\Security\PasswordMigrationAuthenticator
        arguments:
            - "@security.password_encoder"
            - "@old_password_encoder"
            - "@doctrine.orm.entity_manager"
