# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    # app.password_migration_authenticator:
    #     class:     AppBundle\Security\PasswordMigrationAuthenticator
    #     arguments:
    #         - "@security.encoder_factory"
    #         - "@doctrine.orm.entity_manager"

    app.login_listener:
        class: AppBundle\EventListener\LoginListener
        tags:
            - { name: kernel.event_listener, event: security.interactive_login }
        arguments:
            - "@security.encoder_factory"
            - "@doctrine.orm.entity_manager"
