version: '2'
services:
  php:
    build: ./docker/php/
    depends_on:
      - mysql
    environment:
      TIMEZONE: Europe/Paris
      XDEBUG_REMOTE_HOST: 10.200.10.1
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini:ro
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
      - ./app:/var/www/app
    working_dir: /var/www/app

  # I am naming the Nginx container as "webserver" so that it can be changed
  # to any other web server
  webserver:
    build: ./docker/nginx/
    depends_on:
      - php
    volumes_from:
      - php
    volumes:
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80

  mysql:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: root_password_test
      MYSQL_DATABASE: db_test
      MYSQL_USER: user_test
      MYSQL_PASSWORD: password_test
    ports:
      - "3306:3306"
