version: '2'
services:
  php:
    image: php:7.0-fpm
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini:ro
      - ./app:/var/www/app
    working_dir: /var/www/app

  # I am naming the Nginx container as "webserver" so that it can be changed
  # to any other web server
  webserver:
    build: ./docker/nginx/
    depends_on:
      - php
    volumes_from:
      - php
    volumes:
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80
